#docker-compose up -d
#docker-compose exec mysql bash
#mysql -uroot -p goexpert
#create table products (id varchar(255), name varchar(80), price decimal(10,2), primary key(id));
version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: always
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goexpert
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306

